import type { PatternEntry } from "../schemas/PatternSchemas.js";

/**
 * Emergency fallback patterns compiled into the JS output.
 * Used when pattern library files are missing or integrity verification fails.
 * One representative pattern per flag group for minimum viable detection.
 */
export const FALLBACK_PATTERNS: PatternEntry[] = [
    // --- general scope (StaticCheckService) ---
    {
        id: "fallback-xss-script-tag",
        name: "Script tag injection",
        pattern: "<script\\b[^>]*>([\\s\\S]*?)<\\/script>",
        flags: "gim",
        severity: "high",
        category: "xss",
        flagGroup: "hasXSS",
        scope: "general",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-sqli-keyword-pairs",
        name: "SQL keyword pairs",
        pattern: "\\b(SELECT|INSERT|UPDATE|DELETE|DROP|UNION|ALTER|CREATE|TRUNCATE)\\s+(FROM|INTO|TABLE|DISTINCT)\\b",
        flags: "gim",
        severity: "critical",
        category: "sqli",
        flagGroup: "hasSQLi",
        scope: "general",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-sqli-tautology",
        name: "SQL tautology (OR 1=1)",
        pattern: "['\";]\\s+OR\\s+['\"]?1['\"]?\\s*=\\s*['\"]?1['\"]?",
        flags: "gim",
        severity: "critical",
        category: "sqli",
        flagGroup: "hasSQLi",
        scope: "general",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-shell-metacharacters",
        name: "Shell metacharacters",
        pattern: "[&|;`$]",
        flags: "g",
        severity: "high",
        category: "shell_injection",
        flagGroup: "hasShellInjection",
        scope: "skill",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },

    // --- skill scope (SkillScanService) ---
    {
        id: "fallback-hidden-instructions",
        name: "Hidden instructions in HTML comments",
        pattern: "<!--[\\s\\S]*?(ignore|override|bypass|secret|hidden)[\\s\\S]*?-->",
        flags: "gi",
        severity: "medium",
        category: "obfuscation",
        flagGroup: "hasHiddenInstructions",
        scope: "skill",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-dangerous-tools",
        name: "Dangerous bash commands",
        pattern: "(?:^|\\s|```)(bash|sh|zsh)?\\s*(rm\\s+-rf|dd\\s+if=|mkfs|format)",
        flags: "gim",
        severity: "critical",
        category: "shell_injection",
        flagGroup: "hasDangerousToolUsage",
        scope: "skill",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-sensitive-file-access",
        name: "System password file access",
        pattern: "\\/etc\\/(passwd|shadow|sudoers)",
        flags: "gi",
        severity: "high",
        category: "data_exfiltration",
        flagGroup: "hasSensitiveFileAccess",
        scope: "skill",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-obfuscation-base64",
        name: "Base64 encoded content",
        pattern: "[A-Za-z0-9+/]{40,}={0,2}",
        flags: "g",
        severity: "medium",
        category: "obfuscation",
        flagGroup: "hasObfuscation",
        scope: "skill",
        detection: { mode: "threshold", countThreshold: 5, singleMatchLength: 200 },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-social-engineering",
        name: "Urgency/authority language",
        pattern: "\\b(official|urgent|critical|immediate|security update|required|mandatory)\\b",
        flags: "gi",
        severity: "medium",
        category: "social_engineering",
        flagGroup: "hasSocialEngineering",
        scope: "skill",
        detection: { mode: "threshold", countThreshold: 2 },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: [],
    },
    {
        id: "fallback-network-exfiltration",
        name: "URL parameter exfiltration",
        pattern: "https?:\\/\\/(?!(?:localhost|127\\.0\\.0\\.1|github\\.com|npmjs\\.com|api\\.github\\.com))[\\w.-]+.*?[\\?&](data|key|token|secret|password)=",
        flags: "gi",
        severity: "critical",
        category: "data_exfiltration",
        flagGroup: "hasNetworkExfiltration",
        scope: "skill",
        detection: { mode: "simple" },
        enabled: true,
        source: "original",
        cveRefs: [],
        dateAdded: "2025-01-01",
        whitelistedDomains: ["localhost", "127.0.0.1", "github.com", "npmjs.com", "api.github.com"],
    },
];
