import assert from "node:assert/strict";
import { AnalysisBudget } from "../../ai/budget.js";
import { limitsSchema } from "../../ai/config.js";
import { emptyUsage, estimateCost, UsageLedger } from "../../ai/usage.js";

const limits = limitsSchema.parse({});
const budget = new AnalysisBudget("prompt", limits);
assert.equal(budget.reserveAttempt().ok, true);
assert.equal(budget.reserveAttempt().ok, true);
assert.equal(budget.reserveAttempt().ok, true);
assert.equal(budget.reserveAttempt().ok, false, "all retry attempts count toward task cap");
const skill = new AnalysisBudget("skill", limits);
for (let i = 0; i < 6; i++) assert.equal(skill.reserveAttempt().ok, true);
assert.equal(skill.reserveAttempt().ok, false);
const shadow = new AnalysisBudget("prompt", limits);
assert.equal(shadow.reserveAttempt({ optional: true }).ok, false, "shadow needs a prior authoritative reservation");
shadow.authorizeShadow();
for (let i = 0; i < 3; i++) assert.equal(shadow.reserveAttempt({ optional: true }).ok, true);
assert.equal(shadow.reserveAttempt({ optional: true }).ok, false);
assert.equal(shadow.reserveAttempt().ok, true, "shadow cannot spend required attempts");
const money = new AnalysisBudget("prompt", limits, { maxUsd: 0.01 });
assert.equal(money.reserveAttempt().ok, false, "unknown estimate cannot be treated as zero");
const reservation = money.reserveAttempt({ estimatedUsd: 0.008 });
assert.equal(reservation.ok, true);
assert.equal(money.reserveAttempt({ estimatedUsd: 0.008 }).ok, false);
if (reservation.ok) money.reconcile(reservation.id, 0.001);
assert.equal(money.reserveAttempt({ estimatedUsd: 0.008 }).ok, true);
const expired = new AnalysisBudget("prompt", limits, { deadlineMs: Date.now() - 1 });
assert.equal(expired.reserveAttempt().ok, false);
const usage = { ...emptyUsage(), inputTokens: 100, outputTokens: 20, cachedReadTokens: 25, reasoningTokens: 5 };
const prices = { version: "fixture", inputPerMillion: 1, outputPerMillion: 2, cachedReadPerMillion: 0.1, cacheWritePerMillion: 1 };
assert.equal(estimateCost(usage, prices), 0.0001175, "cached subset replaces full input cost; reasoning subset is not added twice");
assert.equal(estimateCost(emptyUsage(), prices), null);
assert.equal(estimateCost(usage), null);
const ledger = new UsageLedger();
ledger.record("one", usage, prices);
ledger.record("one", usage, prices);
assert.equal(ledger.summary().usage.inputTokens, 100, "one actual call accounts once");
ledger.record("two", emptyUsage(), prices);
assert.equal(ledger.summary().estimatedUsd, null, "partly unknown aggregate cost stays unknown");
console.log("PASS task budget, reservations and usage accounting");
