import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DescriptorAnalysisService } from "../../services/DescriptorAnalysisService.js";
import { JudgmentService } from "../../services/JudgmentService.js";
import { McpToolScanner } from "../../services/McpToolScanner.js";
import { PatternService } from "../../services/PatternService.js";
import { loadAIConfig, parseAIConfig } from "../../ai/config.js";
const off = loadAIConfig({});
const shadow = parseAIConfig({ ...off.config, typesafe: { ...off.config.typesafe, descriptor: "shadow" } });
const local = new McpToolScanner(new PatternService());
const baseline = new DescriptorAnalysisService(local, new JudgmentService(off));
let calls = 0;
const service = new DescriptorAnalysisService(local, new JudgmentService(shadow, { apiKey: "fixture", fetch: async (_url, init) => {
    calls++;
    const request = JSON.parse(String(init?.body));
    const state = JSON.parse(request.state);
    assert.equal(state.expectedPoisoning, undefined);
    const selected = Object.keys(request.questions.evidence.criteria).find((key) => key !== "none")!;
    return new Response(JSON.stringify({ model: "jev-1.13.0", answers: { poison: { type: "noul", noul: .99 }, evidence: { type: "choice", choice: selected, confidence: .99,
        probabilities: Object.fromEntries(Object.keys(request.questions.evidence.criteria).map((key) => [key, key === selected ? 1 : 0])) } }, usage: { input_tokens: 50, output_tokens: 20 } }));
} }));
const fixtures = JSON.parse(readFileSync("src/test/fixtures/ai/descriptors/development.json", "utf8")) as Array<{ id: string; tool: Record<string, unknown> }>;
for (const fixture of fixtures) {
    const reference = local.scan({ tool: fixture.tool });
    const plain = await baseline.analyze({ tool: fixture.tool });
    const report = await service.analyze({ tool: fixture.tool });
    assert.deepEqual(report.local, reference, fixture.id);
    for (const key of ["safe", "decision", "overallSeverity", "categories", "findings"] as const) assert.deepEqual(report[key], plain[key], `shadow must preserve ${key}`);
    assert.equal(report.configHash, shadow.hash);
    assert.equal(plain.routing[0].reason, "mode_off");
    assert.equal(report.routing[0].status, "attempted");
    assert.equal(report.coverage.find((entry) => entry.check === "descriptor_judgment")!.required, false);
    assert.ok(report.shadow?.judgments.result?.status === "ok");
    assert.equal(report.judgments, null);
    assert.ok(report.shadow.judgments.result.value.evidence.type === "choice");
    assert.equal(report.shadow.evidence!.id, report.shadow.judgments.result.value.evidence.choice);
    assert.equal(report.safe, report.decision === "allow");
}
const tool = { name: "weather", description: "Returns public forecasts only." };
const first = await service.analyze({ tool });
const before = calls;
const drifted = await service.analyze({ tool, priorHash: "old hash" });
assert.equal(drifted.shadow!.judgments.cache, "hit"); assert.equal(calls, before);
assert.equal(drifted.routing[0].reason, "cache_hit"); assert.equal(drifted.routing[0].status, "skipped");
assert.equal(first.local.drift, false); assert.equal(drifted.local.drift, true);
await service.analyze({ tool: { ...tool, description: "Different public forecast text." } }); assert.equal(calls, before + 1);
const wide = Object.fromEntries(Array.from({ length: 512 }, (_, i) => [`field${i}`, "text"]));
const wideReport = await service.analyze({ tool: wide });
assert.equal(wideReport.local.inspectedFields.length, 512);
assert.ok(wideReport.shadow?.judgments.result?.status === "unavailable");
assert.equal(wideReport.shadow.judgments.result.code, "unsupported");
assert.equal(wideReport.safe, true, "unsupported optional judgment cannot change scoped local result");
await assert.rejects(service.analyze({ tool: { description: "x".repeat(100001) } }), { limit: "characters" });
let deep: Record<string, unknown> = { text: "end" };
for (let i = 0; i < 10000; i++) deep = { child: deep };
const callsBeforeDeep = calls;
const noLocal = new DescriptorAnalysisService({ scan() { throw new Error("local scanner must not see oversized input"); } } as unknown as McpToolScanner, service.judgments);
await assert.rejects(noLocal.analyze({ tool: deep }), { limit: "depth" });
assert.equal(calls, callsBeforeDeep);
const missing = new DescriptorAnalysisService(local, new JudgmentService(shadow));
const unavailable = await missing.analyze({ tool });
assert.ok(unavailable.shadow?.judgments.result?.status === "unavailable");
assert.equal(unavailable.shadow.judgments.result.code, "not_configured"); assert.equal(unavailable.safe, true);
assert.equal(unavailable.routing[0].reason, "not_configured"); assert.equal(unavailable.routing[0].status, "skipped");
const lowRisk = new DescriptorAnalysisService(local, new JudgmentService(shadow, { apiKey: "fixture", fetch: async (_url, init) => {
    const request = JSON.parse(String(init?.body));
    const ids = Object.keys(request.questions.evidence.criteria);
    return new Response(JSON.stringify({ model: "jev-1.13.0", answers: { poison: { type: "noul", noul: .01 }, evidence: { type: "choice", choice: ids[1], confidence: .01, probabilities: Object.fromEntries(ids.map((id) => [id, 1 / ids.length])) } }, usage: { input_tokens: 50, output_tokens: 20 } }));
} }));
assert.equal((await lowRisk.analyze({ tool })).shadow!.evidence, null, "unused speculative evidence is ignored for low poisoning");
const timedSnapshot = parseAIConfig({ ...shadow.config, limits: { ...shadow.config.limits, judgmentTimeoutMs: 20 } });
let timedCalls = 0;
const timed = new DescriptorAnalysisService(local, new JudgmentService(timedSnapshot, { apiKey: "fixture", fetch: async (_url, init) => {
    timedCalls++; return new Promise((_resolve, reject) => init?.signal?.addEventListener("abort", () => reject(new Error("aborted")), { once: true }));
} }));
const [owner, waiter] = await Promise.all([timed.analyze({ tool }), timed.analyze({ tool })]);
assert.equal(timedCalls, 1);
assert.equal(owner.shadow!.judgments.cache, "miss"); assert.equal(waiter.shadow!.judgments.cache, "shared");
assert.equal(owner.routing[0].status, "attempted"); assert.equal(waiter.routing[0].status, "skipped");
assert.equal(owner.shadow!.judgments.result?.meta.callId, waiter.shadow!.judgments.result?.meta.callId);
console.log("PASS descriptor shadow baseline equality, attributable evidence, complete limits and drift outside cache");
