import assert from "node:assert/strict";
import { loadCorpus, sha256, validateCases } from "../../evaluation/Corpus.js";
import { summarizeObservations, repeatedAnswerChanges, type EvaluationObservation } from "../../evaluation/Metrics.js";
const corpus = loadCorpus("evaluations/ai/datasets/synthetic-stress-v1/manifest.json");
assert.equal(corpus.cases.length, 1200);
assert.throws(() => loadCorpus("evaluations/ai/datasets/synthetic-stress-v1/manifest.json", { acceptance: true }));
const first = corpus.cases[0];
assert.throws(() => validateCases([first, first]), /Duplicate/);
assert.throws(() => validateCases([{ ...first, input: { prompt: "changed" } }]), /hash/);
const other = { ...first, id: "other", partition: "held-out", input: { text: "different" }, sourceSha256: sha256(JSON.stringify({ text: "different" })) };
assert.throws(() => validateCases([first, other]), /family/);
assert.throws(() => validateCases([other], { knownFamilies: { [first.family]: "development" } }), /family/);
const observation = (id: string, risk: boolean, decision: EvaluationObservation["decision"]): EvaluationObservation => ({ id, family: "family-" + id, risk, severity: "high", decision, coverageComplete: true, elapsedMs: Number(id) * 10, estimatedUsd: .01, attempts: 1 });
const rows = [observation("1", true, "block"), observation("2", false, "allow"), observation("3", true, "allow"), observation("4", false, "block"), observation("5", false, "review"), observation("6", true, "unavailable")];
const summary = summarizeObservations(rows);
assert.equal(summary.classified, 4); assert.equal(summary.accuracyAmongClassified, .5); assert.equal(summary.review, 1); assert.equal(summary.unavailable, 1); assert.equal(summary.missedHighCritical, 1);
assert.equal(summary.latency.p50Ms, 30); assert.equal(summary.latency.p95Ms, 60);
assert.equal(summarizeObservations([{ ...rows[0], estimatedUsd: null }]).estimatedUsd, null);
assert.equal(repeatedAnswerChanges([rows, rows.map((item) => item.id === "1" ? { ...item, decision: "review" } : item)]).changed, 1);
assert.throws(() => validateCases([{ ...first, input: { tool: null }, sourceSha256: sha256(JSON.stringify({ tool: null })) }]));
assert.throws(() => validateCases([{ ...first, task: "prompt", input: { prompt: 42 }, sourceSha256: sha256(JSON.stringify({ prompt: 42 })) }]));
assert.equal(repeatedAnswerChanges([rows]).changed, null);
console.log("PASS immutable corpus provenance, partition isolation and abstention-aware metrics");
