import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { loadAIConfig, parseAIConfig } from "../../ai/config.js";
import { describeAiConfig } from "../../scripts/checkAiConfig.js";
import { runProbe } from "../../scripts/probeAi.js";
import { loadPriceCard } from "../../ai/pricing.js";
const snapshot = loadAIConfig({});
const config = spawnSync(process.execPath, ["dist/scripts/checkAiConfig.js"], { encoding: "utf8", env: { PATH: process.env.PATH, HOME: process.env.HOME } });
assert.equal(config.status, 0, config.stderr);
assert.equal(JSON.parse(config.stdout).inferencePerformed, false);
const readiness = describeAiConfig(snapshot, {});
const geminiReadiness = readiness.profiles.find((profile) => profile.name === "legacy-gemini")!;
const anthropicReadiness = readiness.profiles.find((profile) => profile.name === "legacy-anthropic")!;
assert.equal(geminiReadiness.credentialEnvironmentVariable, "GEMINI_API_KEY");
assert.deepEqual(geminiReadiness.enabledRoles, ["semantic", "patternDraft"]);
assert.equal(geminiReadiness.credentialRequired, true);
assert.equal(anthropicReadiness.credentialEnvironmentVariable, "ANTHROPIC_API_KEY");
assert.deepEqual(anthropicReadiness.enabledRoles, []);
assert.equal(anthropicReadiness.credentialRequired, false);
assert.deepEqual(readiness.missingCredentialEnvironmentVariables, ["GEMINI_API_KEY"]);
assert.equal(readiness.typesafe.credentialRequired, false);
const enabled = describeAiConfig(snapshot, { TASTE_TESTER_ENABLED: "true", ANTHROPIC_API_KEY: "never-output-this-value" });
assert.deepEqual(enabled.profiles.find((profile) => profile.name === "legacy-anthropic")!.enabledRoles, ["taster", "monitor"]);
assert.ok(!JSON.stringify(enabled).includes("never-output-this-value"));
let calls = 0;
const fetch = async () => { calls++; throw new Error("must not dispatch"); };
for (const args of [[], ["--live"], ["--live", "--profile", "legacy-gemini", "--max-requests", "1", "--max-usd", "1"], ["--live", "--profile", "legacy-gemini", "--max-requests", "0", "--max-usd", "1", "--pricing", "config/ai-pricing.example.json"]]) {
    await assert.rejects(runProbe(args, { snapshot, env: { GEMINI_API_KEY: "fake" }, fetch }));
}
assert.equal(calls, 0);
assert.ok(loadPriceCard("config/ai-pricing.example.json").rates["typesafe:jev-1.13.0"]);
const configured = parseAIConfig({ ...snapshot.config, profiles: { ...snapshot.config.profiles, probe: { provider: "anthropic", model: "claude-sonnet-5", maxOutputTokens: 1024 } } });
const fixture = JSON.parse(readFileSync("src/test/fixtures/ai/providers/anthropic.json", "utf8")).success;
const probeArgs = ["--live", "--profile", "probe", "--max-requests", "1", "--max-usd", "1", "--pricing", "config/ai-pricing.example.json"];
const success = await runProbe(probeArgs, { snapshot: configured, env: { ANTHROPIC_API_KEY: "fake" }, fetch: async () => { calls++; return new Response(JSON.stringify(fixture)); } });
assert.equal(success.status, "ok");
assert.equal(success.actualAttempts, 1);
assert.equal(success.qualification, false);
assert.equal(success.usage.estimatedUsd, .000431);
const expensive = await runProbe(probeArgs.map((item, index, args) => args[index - 1] === "--max-usd" ? "0.00000001" : item), { snapshot: configured, env: { ANTHROPIC_API_KEY: "fake" }, fetch });
assert.equal(expensive.status, "unavailable");
assert.equal(expensive.actualAttempts, 0);
assert.equal(calls, 1);
const openaiConfig = parseAIConfig({ ...snapshot.config, profiles: { ...snapshot.config.profiles, probe: { provider: "openai", model: "gpt-6-astra", maxOutputTokens: 1024 } } });
const openaiFixture = JSON.parse(readFileSync("src/test/fixtures/ai/providers/openai.json", "utf8")).success;
const pricedOpenai = await runProbe(probeArgs, { snapshot: openaiConfig, env: { OPENAI_API_KEY: "fake" }, fetch: async () => new Response(JSON.stringify(openaiFixture)) });
assert.equal(pricedOpenai.usage.estimatedUsd, .00301, "known cache writes must be priced without double charging input tokens");
delete openaiFixture.usage.input_tokens_details.cache_write_tokens;
const unknownWriteCost = await runProbe(probeArgs, { snapshot: openaiConfig, env: { OPENAI_API_KEY: "fake" }, fetch: async () => new Response(JSON.stringify(openaiFixture)) });
assert.equal(unknownWriteCost.usage.estimatedUsd, null, "missing billed cache-write counts remain unknown rather than zero");
console.log("PASS offline configuration and explicit probe limits");
