import assert from "node:assert/strict";
import { AnalysisBudget } from "../../ai/budget.js";
import { limitsSchema } from "../../ai/config.js";
import { emptyUsage } from "../../ai/usage.js";
const limits = limitsSchema.parse({});
const parent = new AnalysisBudget("descriptor", limits, { deadlineMs: Date.now() + 15, maxUsd: .1 });
const envelope = parent.reserveSharedCall(limits, { deadlineMs: Date.now() + 500, maxAttempts: 2, estimatedUsd: .04 });
assert.ok(envelope.ok);
assert.equal(parent.attempts, 0, "held capacity is not actual inference");
assert.equal(parent.reserveAttempt({ estimatedUsd: .04 }).ok, false, "held money cannot be spent twice");
await new Promise((resolve) => setTimeout(resolve, 20));
const first = envelope.budget.reserveAttempt({ estimatedUsd: .04 });
assert.ok(first.ok, "surviving coalesced caller may complete after original caller deadline");
assert.equal(parent.attempts, 1);
assert.equal(envelope.budget.usage, parent.usage, "actual usage has one owning ledger");
envelope.budget.usage.record("shared-call", { ...emptyUsage(), inputTokens: 20, outputTokens: 10 }, { version: "test", inputPerMillion: .042, outputPerMillion: 0 });
envelope.budget.usage.record("shared-call", emptyUsage());
assert.equal(parent.usage.summary().calls, 1);
envelope.budget.reconcile(first.id, .001);
envelope.release(); envelope.release();
assert.equal(parent.attempts, 1);
assert.equal(envelope.budget.reserveAttempt({ estimatedUsd: .04 }).ok, false, "released envelope cannot dispatch late work");

const request = new AnalysisBudget("prompt", limits, { maxUsd: .11 });
const shared = request.reserveSharedCall(limits, { deadlineMs: Date.now() + 500, estimatedUsd: .05 });
assert.ok(shared.ok);
assert.ok(request.reserveAttempt({ estimatedUsd: .01 }).ok);
assert.equal(request.reserveAttempt({ estimatedUsd: 0 }).ok, false, "held attempt capacity cannot be bypassed");
shared.release();
assert.ok(request.reserveAttempt({ estimatedUsd: .05 }).ok, "unused reservations release both attempts and money");
assert.ok(request.reserveAttempt({ estimatedUsd: .05 }).ok);
assert.equal(request.attempts, 3);

const optionalParent = new AnalysisBudget("skill", limits);
assert.equal(optionalParent.reserveSharedCall(limits, { optional: true, deadlineMs: Date.now() + 100 }).ok, false);
optionalParent.authorizeShadow();
const optional = optionalParent.reserveSharedCall(limits, { optional: true, deadlineMs: Date.now() + 100 });
assert.ok(optional.ok);
for (let i = 0; i < 6; i++) assert.ok(optionalParent.reserveAttempt().ok, "shadow uses its own attempt pool");
assert.ok(optional.budget.reserveAttempt({ optional: true }).ok);
optional.release();
const capped = new AnalysisBudget("descriptor", limits, { maxUsd: 1 });
assert.equal(capped.reserveSharedCall(limits, { deadlineMs: Date.now() + 100 }).ok, false, "unknown rate refuses capped dispatch");
const tiny = new AnalysisBudget("descriptor", limits, { maxUsd: .06 });
const one = tiny.reserveSharedCall(limits, { deadlineMs: Date.now() + 100, estimatedUsd: .05 });
assert.ok(one.ok); assert.ok(one.budget.reserveAttempt({ estimatedUsd: .05 }).ok);
assert.equal(one.budget.reserveAttempt({ estimatedUsd: .05 }).ok, false, "only affordable slots are reserved");
one.release();
assert.equal(capped.reserveSharedCall(limits, { deadlineMs: Date.now() + 60_000, estimatedUsd: .1 }).ok, false, "shared provider lifetime remains bounded");
const shadowCap = new AnalysisBudget("prompt", limits, { maxUsd: .2 });
assert.ok(shadowCap.reserveAttempt({ estimatedUsd: .1 }).ok);
shadowCap.authorizeShadow();
assert.equal(shadowCap.reserveAttempt({ optional: true, estimatedUsd: .1 }).ok, false);
shadowCap.authorizeShadow({ requiredWorkComplete: true });
assert.ok(shadowCap.reserveAttempt({ optional: true, estimatedUsd: .1 }).ok);
assert.equal(shadowCap.reserveAttempt({ estimatedUsd: 0 }).ok, false, "required pool cannot reopen after authorizing remaining spend");
const shortLimits = limitsSchema.parse({ analysisDeadlineMs: 15, judgmentTimeoutMs: 1000 });
const shortRequest = new AnalysisBudget("descriptor", shortLimits);
const sharedDeadline = Date.now() + 500;
const independent = shortRequest.reserveSharedCall(shortLimits, { deadlineMs: sharedDeadline });
assert.ok(independent.ok);
assert.equal(independent.budget.deadlineMs, sharedDeadline, "shared deadline cannot be clamped by original request duration");
independent.release();
const overrun = new AnalysisBudget("descriptor", limits, { maxUsd: .1 });
const held = overrun.reserveSharedCall(limits, { deadlineMs: Date.now() + 100, estimatedUsd: .04 });
assert.ok(held.ok);
const other = overrun.reserveAttempt({ estimatedUsd: .02 }); assert.ok(other.ok);
overrun.reconcile(other.id, .11);
assert.equal(held.budget.reserveAttempt({ estimatedUsd: .04 }).ok, false, "reconciled overrun must stop prepaid dispatch too");
held.release();
console.log("PASS shared judgment reservations, independent deadline, single usage and unused-capacity release");
