import { z } from "zod";
import { severitySchema } from "./schemas.js";

export const securityCategories = ["prompt_injection", "social_engineering", "obfuscation", "multilingual",
    "unicode_smuggling", "policy_puppetry", "markdown_exfil", "many_shot"] as const;
export function semanticSchema(sourceIds: readonly string[] = ["input"]) {
    // IDs are generated by the caller. They are constrained in both the native
    // schema and the local parser; model-supplied paths are never trusted.
    const sourceId = sourceIds.length ? z.enum([...sourceIds] as [string, ...string[]]) : z.string();
    return z.strictObject({
        verdict: z.enum(["benign", "suspicious", "malicious", "undetermined"]),
        severity: severitySchema,
        categories: z.array(z.enum(securityCategories)).max(8),
        explanation: z.string().min(1).max(4000),
        evidenceIds: z.array(sourceId).max(sourceIds.length ? 64 : 0),
        isInjection: z.boolean(),
        selfReportedConfidence: z.number().finite().min(0).max(1).nullable(),
    });
}
export const semanticFindingSchema = semanticSchema();
export type SemanticFinding = z.infer<typeof semanticFindingSchema>;
export const capabilityBuckets = ["privateDataRead", "untrustedContentFetch", "externalEgress"] as const;
export function capabilityAssessmentSchema(sourceIds: readonly string[]) {
    // Native grammars cannot encode z.never's `not: {}`. An empty source set
    // instead requires an empty array; the local parser enforces this even
    // when a provider expresses the zero bound only as schema guidance.
    const id = sourceIds.length ? z.enum([...sourceIds] as [string, ...string[]]) : z.string();
    const ids = z.array(id).max(sourceIds.length ? 64 : 0);
    const bucket = z.strictObject({ state: z.enum(["present", "absent", "unknown"]), evidenceIds: ids });
    return z.strictObject({ completeDeclaredScope: z.boolean(), restrictionEvidenceIds: ids,
        privateDataRead: bucket, untrustedContentFetch: bucket, externalEgress: bucket,
        explanation: z.string().min(1).max(4000) });
}
export type CapabilityAssessment = z.infer<ReturnType<typeof capabilityAssessmentSchema>>;
export function skillReasoningSchema(capabilitySourceIds: readonly string[], referenceIds: readonly string[]) {
    const id = referenceIds.length ? z.enum([...referenceIds] as [string, ...string[]]) : z.string();
    return z.strictObject({ security: semanticFindingSchema, capabilities: capabilityAssessmentSchema(capabilitySourceIds).nullable(),
        references: z.array(z.strictObject({ id, classification: z.enum(["model", "not_model", "unknown"]) })).max(referenceIds.length ? 64 : 0) });
}
/** Output evidence IDs were already validated against generated source IDs at
 * the provider boundary. Reports retain those IDs without inventing paths. */
export const sourcedSemanticReportSchema = semanticFindingSchema.extend({ evidenceIds: z.array(z.string()).max(64) });
export const patternDraftSchema = z.strictObject({ patterns: z.array(z.strictObject({
    pattern: z.string().min(1).max(4000), flags: z.string().max(8), description: z.string().max(2000),
    category: z.enum(["xss", "sqli", "shell_injection", "directory_traversal", "ssrf"]), severity: severitySchema,
})).max(20) });
export function nativeJsonSchema(schema: z.ZodType): Record<string, unknown> {
    const result = z.toJSONSchema(schema, { target: "draft-7" });
    delete result.$schema;
    return result as Record<string, unknown>;
}

export const monitorReportSchema = z.strictObject({
    intents: z.array(z.strictObject({
        action: z.enum(["fetch_url", "read_file", "exec_shell", "send_email", "transfer_funds", "navigate_browser", "write_memory", "query_database", "unknown"]),
        target: z.string().max(4000), severity: z.enum(["safe", "medium", "high", "critical"]),
        atlasTechniques: z.array(z.string().max(100)).max(20), rationale: z.string().max(4000).nullable(),
    })).max(40),
    monitorVerdict: z.enum(["clean", "suspicious", "malicious"]), monitorRationale: z.string().min(1).max(4000), severity: z.enum(["safe", "medium", "high", "critical"]),
});
