import { z } from "zod";
import { severitySchema } from "./schemas.js";

export const securityCategories = ["prompt_injection", "social_engineering", "obfuscation", "multilingual",
    "unicode_smuggling", "policy_puppetry", "markdown_exfil", "many_shot"] as const;
export function semanticSchema(sourceIds: readonly string[] = ["input"]) {
    // IDs are generated by the caller. They are constrained in both the native
    // schema and the local parser; model-supplied paths are never trusted.
    const sourceId = sourceIds.length ? z.enum([...sourceIds] as [string, ...string[]]) : z.never();
    return z.strictObject({
        verdict: z.enum(["benign", "suspicious", "malicious", "undetermined"]),
        severity: severitySchema,
        categories: z.array(z.enum(securityCategories)).max(8),
        explanation: z.string().min(1).max(4000),
        evidenceIds: z.array(sourceId).max(64),
        isInjection: z.boolean(),
        selfReportedConfidence: z.number().finite().min(0).max(1).nullable(),
    });
}
export const semanticFindingSchema = semanticSchema();
export type SemanticFinding = z.infer<typeof semanticFindingSchema>;
export const patternDraftSchema = z.strictObject({ patterns: z.array(z.strictObject({
    pattern: z.string().min(1).max(4000), flags: z.string().max(8), description: z.string().max(2000),
    category: z.enum(["xss", "sqli", "shell_injection", "directory_traversal", "ssrf"]), severity: severitySchema,
})).max(20) });
export function nativeJsonSchema(schema: z.ZodType): Record<string, unknown> {
    const result = z.toJSONSchema(schema, { target: "draft-7" });
    delete result.$schema;
    return result as Record<string, unknown>;
}
